### PR TITLE
Fix taskcluster CI failures for signing infra

### PR DESCRIPTION
**Pull request by rhelmer**

### CODE REVIEW

**Comment by rhelmer** [comment]
DO NOT MERGE, let's discuss a little first!

@Dexterp37 @escapewindow and I discussed this today and dug into why our build is failing in confusing ways, turns out to be two issues:

1. CI is finding the `support/package.json` and treating it like an add-on :(
2. CI runs `yarn lint` without running `build` first

My commit addressing the first feels way too hacky to me. The lint thing is fine I guess but we really need to clean up our build targets :)

**Review by escapewindow — APPROVED** [review]
This works for me. Another option is to green up the support/package.json build.

**Review by Dexterp37 — CHANGES_REQUESTED** [review]
Do you have a link to the failure log on TC? I don't think we should really rename the package.json from our support library to accomodate TC..

**Comment by rhelmer** [comment]
> 
> 
> Do you have a link to the failure log on TC? I don't think we should really rename the package.json from our support library to accomodate TC..

Yes I totally agree (which is why I didn't want to merge this and gave that change the commit message I did as a reminder to myself!) but I'm not sure how this should be handled. Without changes on the TC side, the only things I can think of are:

1. rename support/package.json in the repo and have the build system rename it
2. move support library to a different repo

(2) is cleaner but more of a hassle obviously... (1) I've only done the rename part and not the build system part (mostly because I'm not really sold on doing it this way)

**Comment by rhelmer** [comment]
After discussion, we decided that the best way forward would be to get the build working for the primary task now, and tackle excluding the `support/package.json` in https://github.com/mozilla-ion/ion-core-addon/issues/214

**Pull request merged**
