### PR TITLE
Release 0.7.0

### PR DESCRIPTION
**Pull request by Dexterp37**
See the [original changelog](https://github.com/mozilla-rally/core-addon/releases/tag/v0.7.0).

### CODE REVIEW

**Comment by Dexterp37** [comment]
The CI will fail until mozilla-extensions/xpi-manifest#95 is merged

**Comment by Dexterp37** [comment]
> 
> 
> The CI will fail until [mozilla-extensions/xpi-manifest#95](https://github.com/mozilla-extensions/xpi-manifest/pull/95) is merged

Weird, I would have expected `dep-signing-rally_core` to fail because the above PR was not merged yet. @escapewindow do you know why that wasn't the case?

**Comment by escapewindow** [comment]
You have that reversed. We need to merge this one first.

**Comment by rhelmer** [comment]
`t-test-integration-rally_core` is failing because it is an integration test that requires Firefox to be installed, @escapewindow do we have a way of skipping this target or telling TC which targets to run or is it just hardcoded to `yarn test`?

@Dexterp37 it feels like our options for doing this cleanly are to either:

1. divorce `test-integration` from the `test` target
2. get Firefox installed in the TC environment

(1) seems fine to me since we already run the integration tests in our environment and I don't *think* (2) really buys us any extra assurance, unless maybe we could run the test with the dep-signed output. 

What I would like to do for today is land now so we can get going and explain to reviewers why this fails, and follow-up with (1).

**Comment by rhelmer** [comment]
> `t-test-integration-rally_core` is failing because it is an integration test that requires Firefox to be installed, @escapewindow do we have a way of skipping this target or telling TC which targets to run or is it just hardcoded to `yarn test`?
> 
> @Dexterp37 it feels like our options for doing this cleanly are to either:
> 
>     1. divorce `test-integration` from the `test` target
> 
>     2. get Firefox installed in the TC environment
> 
> 
> (1) seems fine to me since we already run the integration tests in our environment and I don't _think_ (2) really buys us any extra assurance, unless maybe we could run the test with the dep-signed output.
> 
> What I would like to do for today is land now so we can get going and explain to reviewers why this fails, and follow-up with (1).

Maybe also:

3. have our integration test detect the TC environment and no-op in that case

**Review by rhelmer — APPROVED** [review]
Approving with the caveat that we have a known TC-only test failure, ran this by Aki and I will explain to add-on reviewers :)

**Comment by escapewindow** [comment]
> > `t-test-integration-rally_core` is failing because it is an integration test that requires Firefox to be installed, @escapewindow do we have a way of skipping this target or telling TC which targets to run or is it just hardcoded to `yarn test`?

It's hardcoded to run `yarn test` if the `test` target exists.

> > @Dexterp37 it feels like our options for doing this cleanly are to either:
> > ```
> > 1. divorce `test-integration` from the `test` target

This would work.

> > 2. get Firefox installed in the TC environment
> > ```

This may be trickier, but could work. We could also check for the existence of something like ENV `TASKCLUSTER_VOLUMES` or similar: if it exists we're probably on taskcluster, and we can skip integration tests.

> > (1) seems fine to me since we already run the integration tests in our environment and I don't _think_ (2) really buys us any extra assurance, unless maybe we could run the test with the dep-signed output.
> > What I would like to do for today is land now so we can get going and explain to reviewers why this fails, and follow-up with (1).
> 
> Maybe also:
> 
>     1. have our integration test detect the TC environment and no-op in that case

This, or splitting out integration from the `test` target, may be the easiest solutions.

**Comment by rhelmer** [comment]
I filed https://github.com/mozilla-rally/core-addon/issues/292 as a follow-up - thanks!

**Pull request merged**
